version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.5.0
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.1
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
    - 1.32.7
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.1.4
    - 5.2.3
  - dependency-name: vuetify
    versions:
    - 2.4.10
    - 2.4.7
    - 2.4.8
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.13
    - 7.13.15
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.2.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.5
    - 7.13.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.129
    - 0.0.130
    - 0.0.131
    - 0.0.132
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
